# Generated by Django 4.2.5 on 2023-11-02 13:44

from django.db import migrations, models
import module_1.models


class Migration(migrations.Migration):
    dependencies = [
        ("module_1", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="child",
            name="Child_Gender",
            field=models.TextField(
                validators=[module_1.models.gender_check], verbose_name="Пол ребёнка"
            ),
        ),
    ]
