# Generated by Django 4.2.5 on 2023-11-02 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("module_1", "0002_alter_child_child_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="child",
            name="Child_Parent_Code",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="module_1.parent",
                verbose_name="Родитель",
            ),
        ),
    ]
