# Generated by Django 4.2.5 on 2023-11-02 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("module_1", "0003_alter_child_child_parent_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agreement",
            name="Agreement_Administrator_Tabel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="module_1.administrator",
                verbose_name="Администратор, готовящий заявление, являющееся основанием заключения договора",
            ),
        ),
        migrations.AlterField(
            model_name="agreement",
            name="Agreement_Parent_Code",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="module_1.parent",
                verbose_name="Родитель",
            ),
        ),
        migrations.AlterField(
            model_name="agreement",
            name="Agreement_Statement_Code",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="module_1.statement",
                verbose_name="Заявление, являющееся основанием заключения договора",
            ),
        ),
        migrations.AlterField(
            model_name="statement",
            name="Statement_Administrator_Tabel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="module_1.administrator",
                verbose_name="Администратор, готовящий заявление",
            ),
        ),
    ]
