# Generated by Django 4.2.5 on 2023-11-02 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("module_1", "0004_alter_agreement_agreement_administrator_tabel_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statement",
            name="Statement_Parent_Code",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="module_1.parent",
                verbose_name="Родитель",
            ),
        ),
    ]
